#!/bin/bash
NAME="{{cookiecutter.app_name}}"
PORT=8000
SOCKFILE=/www/{{cookiecutter.app_name}}/gunicorn.sock
NUM_WORKERS=3
TIMEOUT=120
USER=root
GROUP=root
LOGFILE=/var/log/gunicorn/$NAME.log
LOGDIR=$(dirname $LOGFILE)
test -d $LOGDIR || mkdir -p $LOGDIR
cd /www/$NAME

echo "Starting $NAME as `whoami`"

source /www/{{cookiecutter.app_name}}-package/bin/activate
exec /www/{{cookiecutter.app_name}}-package/bin/gunicorn \
         -w $NUM_WORKERS -t $TIMEOUT \
        --user=$USER --group=$GROUP --log-level=debug \
        --name=$NAME -b 127.0.0.1:$PORT \
        --bind=unix:$SOCKFILE \
        --env DJANGO_SETTINGS_MODULE={{cookiecutter.app_name}}.settings.prod \
        --log-file=$LOGFILE 2>>$LOGFILE $NAME.wsgi:application
